"""Phase 12: replay verifier -- VERIFIED on a clean set, TAMPERED on each edit.

The sample artifact set is generated by our own Phase 4/11 code (a test
fixture, not fabricated evidence of a real match), then each major field is
altered one at a time.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from police_peer.domain.captures import SubGameResult
from police_peer.domain.crypto import (
    AuditResult,
    AuditVerdict,
    SealedRecord,
    SealedTurnPayload,
    compute_commit_hash,
)
from police_peer.services.artifact_builders import build_log_artifact, build_result_artifact
from police_peer.services.artifact_models import ConfigArtifact
from police_peer.services.artifacts import (
    config_filename,
    load_json,
    log_filename,
    result_filename,
    save_artifact,
)
from police_peer.services.replay_verifier import verify_replay
from police_peer.services.series_runtime import SeriesResult
from police_peer.services.series_scoring import FinalAgreement, SubGameRecord
from police_peer.shared.canonical_json import canonical_json_bytes
from police_peer.shared.config_loader import sha256_hex

CONFIG_DIR = Path(__file__).resolve().parents[2] / "config" / "police"
UID = "abcabcab-1111-2222-3333-444444444444"
GID = "edward-donia"
N_GAMES = 3


def _terms() -> dict:
    with open(CONFIG_DIR / "game.json", encoding="utf-8") as handle:
        return json.load(handle)


def _payload(sub_game: int, step: int) -> SealedTurnPayload:
    return SealedTurnPayload(
        step=step,
        role="police",
        sub_game_number=sub_game,
        state={"position": [step % 7, 0]},
        move="N",
        barrier_placed=None,
        intent="truth",
        hint="north looks fine",
        scent_digest="d" * 64,
        capture_claim=(step % 7, 0),
        claim_response=None,
        win_claim=False,
        timestamp="2026-07-18T00:00:00+00:00",
        nonce=f"{sub_game:032x}{step:032x}",
    )


def _write_bundle(directory: Path) -> None:
    terms = _terms()
    config_sha = sha256_hex(CONFIG_DIR / "game.json")
    records_by_game = []
    for n in range(1, N_GAMES + 1):
        recs = tuple(
            SealedRecord(_payload(n, s), compute_commit_hash(_payload(n, s))) for s in range(2)
        )
        records_by_game.append(recs)
        _save_config_artifact(directory, terms, config_sha, n)
        log = build_log_artifact(UID, GID, n, recs, AuditResult(AuditVerdict.VERIFIED, "ok"))
        save_artifact(log, directory / log_filename(GID, n))
    sub_records = tuple(
        SubGameRecord(n, SubGameResult.CAPTURE, 20, 5, 2, True) for n in range(1, N_GAMES + 1)
    )
    series = SeriesResult(
        sub_records, FinalAgreement(True, "agreed", 20 * N_GAMES, 5 * N_GAMES), "completed", None
    )
    result = build_result_artifact(UID, GID, "deadbeef", GID, config_sha, series)
    save_artifact(result, directory / result_filename(GID))
    # A declaration file sharing the same game_uid.
    decl = {"schema_version": "declaration/1", "game_uid": UID, "game_id": GID, "role": "police"}
    (directory / f"declaration_{GID}.json").write_bytes(canonical_json_bytes(decl) + b"\n")


def _save_config_artifact(directory: Path, terms: dict, config_sha: str, n: int) -> None:
    art = ConfigArtifact(UID, GID, n, config_sha, terms)
    save_artifact(art, directory / config_filename(GID, n))


def test_clean_bundle_is_verified(tmp_path) -> None:
    _write_bundle(tmp_path)
    report = verify_replay(tmp_path)
    assert report.ok is True, report.findings
    assert report.verdict == "VERIFIED"


def _tamper(tmp_path: Path, filename: str, mutate) -> None:
    path = tmp_path / filename
    data = load_json(path)
    mutate(data)
    path.write_bytes(canonical_json_bytes(data) + b"\n")


@pytest.mark.parametrize(
    "filename,mutate,label",
    [
        (result_filename(GID), lambda d: d.__setitem__("game_uid", "different"), "game_uid"),
        (
            log_filename(GID, 1),
            lambda d: d["steps"][0].__setitem__("commit_hash", "0" * 64),
            "hash",
        ),
        (log_filename(GID, 1), lambda d: d["steps"][0].__setitem__("nonce", "f" * 64), "nonce"),
        (log_filename(GID, 1), lambda d: d.__setitem__("steps", d["steps"][:1]), "sequence"),
        (
            log_filename(GID, 2),
            lambda d: d["steps"][0].__setitem__("barrier_placed", [99, 99]),
            "barrier",
        ),
        (
            log_filename(GID, 2),
            lambda d: d["steps"][0].__setitem__("capture_claim", [50, 50]),
            "capture",
        ),
        (
            result_filename(GID),
            lambda d: d["sub_games"][0].__setitem__("police_score", 999),
            "score",
        ),
    ],
)
def test_each_tamper_is_detected(tmp_path, filename, mutate, label) -> None:
    _write_bundle(tmp_path)
    _tamper(tmp_path, filename, mutate)
    report = verify_replay(tmp_path)
    assert report.ok is False, f"{label} tamper not detected"
    assert report.verdict == "TAMPERED"
    assert report.findings


def test_missing_artifacts_reported(tmp_path) -> None:
    report = verify_replay(tmp_path)  # empty dir
    assert report.ok is False
    assert "missing required artifacts" in report.findings[0]


def test_duplicate_sub_game_number_is_detected(tmp_path) -> None:
    """A log file relabeled to claim ANOTHER sub-game's number (while a
    different log silently goes missing in its place) must not slip past as
    if nothing happened -- regression for a gap where a naive
    number-keyed dict lookup would silently keep only the last one."""
    _write_bundle(tmp_path)
    _tamper(tmp_path, log_filename(GID, 2), lambda d: d.__setitem__("sub_game_number", 1))
    report = verify_replay(tmp_path)
    assert report.ok is False
    assert any("duplicate sub_game_number" in f for f in report.findings)
